package lab.oxgame.datasource;

import java.sql.Connection;
import java.sql.SQLException;
import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;

public class DataSource {
	private static HikariConfig config;
	private static HikariDataSource ds;
	/*
	CREATE TABLE rozgrywka(
	 rozgrywka_id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
	 gracz_o VARCHAR(32),
	 gracz_x VARCHAR(32),
	 zwyciezca VARCHAR(1),
	 dataczas_rozgrywki TIMESTAMP NOT NULL
	);
	 */
	static {
		config = new HikariConfig();
		config.setJdbcUrl("jdbc:hsqldb:file:db/rozgrywki");
		config.setUsername("admin");
		config.setPassword("admin");
		config.setMaximumPoolSize(1);
		//config.addDataSourceProperty("cachePrepStmts", "true");
		//config.addDataSourceProperty("prepStmtCacheSize", "250");
		//config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048");
		ds = new HikariDataSource(config);
	}

	private DataSource() {}

	public static Connection getConnection() throws SQLException {
		return ds.getConnection();
	}
}